use crate::spheres::Spheres;

pub static FOLDING_RECIPES: [Spheres; 8] = [
    Spheres {
        zeta: 0,
        theta: 1,
        gamma: 0,
        omega: -1,
        lambda: -1,
        xi: 1,
        epsilon: 0,
        phi: 0,
    },
    Spheres {
        zeta: 1,
        theta: 0,
        gamma: -1,
        omega: 0,
        lambda: 1,
        xi: -1,
        epsilon: 0,
        phi: 0,
    },
    Spheres {
        zeta: -1,
        theta: 1,
        gamma: 0,
        omega: 0,
        lambda: 0,
        xi: -1,
        epsilon: 0,
        phi: 1,
    },
    Spheres {
        zeta: 1,
        theta: -1,
        gamma: 0,
        omega: 0,
        lambda: -1,
        xi: 0,
        epsilon: 1,
        phi: 0,
    },
    Spheres {
        zeta: 0,
        theta: -1,
        gamma: 0,
        omega: 1,
        lambda: 0,
        xi: 0,
        epsilon: -1,
        phi: 1,
    },
    Spheres {
        zeta: -1,
        theta: 0,
        gamma: 1,
        omega: 0,
        lambda: 0,
        xi: 0,
        epsilon: 1,
        phi: -1,
    },
    Spheres {
        zeta: 0,
        theta: 0,
        gamma: -1,
        omega: 1,
        lambda: 0,
        xi: 1,
        epsilon: 0,
        phi: -1,
    },
    Spheres {
        zeta: 0,
        theta: 0,
        gamma: 1,
        omega: -1,
        lambda: 1,
        xi: 0,
        epsilon: -1,
        phi: 0,
    },
];

pub static INVERSION_RECIPES: [Spheres; 2] = [
    Spheres {
        zeta: -1,
        theta: -1,
        gamma: -1,
        omega: -1,
        lambda: 1,
        xi: 1,
        epsilon: 1,
        phi: 1,
    },
    Spheres {
        zeta: 1,
        theta: 1,
        gamma: 1,
        omega: 1,
        lambda: -1,
        xi: -1,
        epsilon: -1,
        phi: -1,
    },
];
